version: "3.7"

services:
  app:
    image: felipeaguiarphp/book-app:latest
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/ # só as configs, não o código
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
  frontend:
    build:
        context: ../book-app-front
        dockerfile: Dockerfile
    container_name: book-app-frontend
    ports:
        - "8080:80"
    networks:
        - laravel

networks:
  laravel:
    driver: bridge
